MODEL_NAME = "phi3"

OLLAMA_URL = "http://localhost:11434/api/generate"

WAKE_THRESHOLD = 0.5

SESSION_TIMEOUT = 20

VOICE_RATE = -25

VOICE_VOLUME = 1.0

ENABLE_STREAMING_TTS = True

MEMORY_SIMILARITY_THRESHOLD = 0.45